### ISSUE TITLE
No puedo loguearme desde raspberry pi 4

### ISSUE THREAD

**Issue by cenosito** [ngosang/docker-amule#21]
No puedo entrar en la web con la contraseña que he puesto en el docke-compose.
La imagen va en una raspberry pi 4.

Meto la contraseña en el campo de la web que se activa nada mas cargarla y no me entra nunca, recarga la pagina y vuelve al mismo punto.

He probado este mismo docker compose en linux y entra perfectamente con la misma contraseña

```
version: "2.1"
services:
  amule:
    image: ngosang/amule
    container_name: amule
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid 
      # GUI_PWD and WEBUI_PWD are only used in initial setup
      - GUI_PWD=1234
      - WEBUI_PWD=1234
      - MOD_AUTO_RESTART_ENABLED=true
      - MOD_AUTO_RESTART_CRON=0 6 * * *
      - MOD_AUTO_SHARE_ENABLED=false
      - MOD_AUTO_SHARE_DIRECTORIES=/incoming;/my_movies
      - MOD_FIX_KAD_GRAPH_ENABLED=true
    ports:
      - "9090:4711" # web ui
      - "4712:4712" # remote gui, webserver, cmd ...
      - "4662:4662" # ed2k tcp
      - "4665:4665/udp" # ed2k global search udp (tcp port +3)
      - "4672:4672/udp" # ed2k udp
    volumes:
      - /home/pi/.amule:/home/amule/.aMule 
      - /home/pi/Downloads:/incoming  
      - /tmp:/temp 
    restart: unless-stopped
```
