### ISSUE TITLE
Unable to auto share directories with subdirectories

### ISSUE THREAD

**Issue by Carlos672** [ngosang/docker-amule#22]
Using Raspberry PI 4 and this compose I am unable to share other folders more than /incoming and /temp

Locally I have this folder that I need to share /media/Disk-5A/compartir/new/
(even /media/Disk-5A/compartir/ is mapped as /incoming, and 'new' is a subfolder, is not shared when the MOD_AUTO_SHARE_ENABLED is True)

This is my compose:

```
version: "2.1"
services:
  amule:
    image: ngosang/amule
    container_name: amule
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      # GUI_PWD and WEBUI_PWD are only used in initial setup
      - GUI_PWD=xxxxx  
      - WEBUI_PWD=xxxxx
      - MOD_AUTO_RESTART_ENABLED=true
      - MOD_AUTO_RESTART_CRON=0 6 * * *
      - MOD_AUTO_SHARE_ENABLED=True
      - MOD_AUTO_SHARE_DIRECTORIES=/incoming;/new;/otra_carpeta;  #/my_movies
      - MOD_FIX_KAD_GRAPH_ENABLED=true
    ports:
      - "4711:4711" # web ui
      - "4712:4712" # remote gui, webserver, cmd ...
      - "4662:4662" # ed2k tcp
      - "4665:4665/udp" # ed2k global search udp (tcp port +3)
      - "4672:4672/udp" # ed2k udp
    volumes:
      - /media/Disk-5A/amule:/home/amule/.aMule
      - /media/Disk-5A/compartir/:/incoming
      - /media/Disk-5A/amule/temp:/temp
    restart: unless-stopped
```
To mention, that MOD_AUTO_SHARE_DIRECTORIES and MOD_AUTO_SHARE_ENABLED were updated after the container was run for the first time.
