### ISSUE TITLE
Missing ports

### ISSUE THREAD

**Issue by barukh27** [ngosang/docker-amule#39]
Hi there!

I'm running a docker image using this docker-compose template:

```
version: "2.1"
services:
  amule:
    image: ngosang/amule
    container_name: amule
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - GUI_PWD=XXXX
      - WEBUI_PWD=XXX
      - MOD_AUTO_RESTART_ENABLED=true
      - MOD_AUTO_RESTART_CRON=0 6 * * *
      - MOD_AUTO_SHARE_ENABLED=false
      - MOD_AUTO_SHARE_DIRECTORIES=/incoming;/my_movies
      - MOD_FIX_KAD_GRAPH_ENABLED=true
      - MOD_FIX_KAD_BOOTSTRAP_ENABLED=true
    ports:
      - "4711:4711" # web ui
      - "4712:4712" # remote gui, webserver, cmd ...
      - "4662:4662" # ed2k tcp
      - "4665:4665/udp" # ed2k global search udp (tcp port +3)
      - "4672:4672/udp" # ed2k udp
    volumes:
      - /mnt/aMule/config:/home/amule/.aMule
      - /mnt/Donwloads:/incoming
      - /mnt/Temp:/temp
    restart: unless-stopped
```

The thing is that the container is running but I can't reach the webui. Portainer doesn't show the ports. If I restart the containers they appear for some time and then they drop.

What am I missing out?

Thank you for your help.

EDIT:

It seems that the container is restarting forever.

The logs say too: chown: /incoming: Operation not permitted
