### ISSUE TITLE
amule not using my dockercompose.yml configuration?

### ISSUE THREAD

**Issue by Itookmyprozac** [ngosang/docker-amule#42]
I'm using Ubuntu server 22.04.3 LTS. 

This is the content of my dockercompose.yml and obviously there is a mistake because amule places the downloaded files in my home (`/home/itook/.aMule/Incoming`) and I also get lowID and firewalled Kad.

```
---
version: "2.1"
services:
  amule:
    image: ngosang/amule
    container_name: amule
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - GUI_PWD=my-password
      - WEBUI_PWD=my-password
      - MOD_AUTO_RESTART_ENABLED=true
      - MOD_AUTO_RESTART_CRON=0 6 * * *
      - MOD_AUTO_SHARE_ENABLED=false
      - MOD_AUTO_SHARE_DIRECTORIES=/almacen1/ALEJANDRO/DESCARGAS/AMULE/Incoming
      - MOD_FIX_KAD_GRAPH_ENABLED=true
      - MOD_FIX_KAD_BOOTSTRAP_ENABLED=true
    ports:
      - "4711:4711" # web ui
      - "4712:4712" # remote gui, webserver, cmd ...
      - "59000:59000" # ed2k tcp
      - "59003:59003/udp" # ed2k global search udp (tcp port +3)
      - "4672:4672/udp" # ed2k udp
    volumes:
      - /home/itook/.aMule
      - /almacen1/ALEJANDRO/DESCARGAS/AMULE/Incoming
      - /almacen1/ALEJANDRO/DESCARGAS/AMULE/Temp
    restart: unless-stopped
```
The ports 59000 and 59003 are open. 

The log after runing `docker compose up --build` using the referenced configuration:

```
 ✔ Container amule  Created                                      0.0s 
Attaching to amule
amule  | Group 1000 already exists. Won't be created.
amule  | Group amule with GID 1000 will be used as amule group.
amule  | User 1000 already exists. Won't be added.
amule  | User amule with UID 1000 will be used as amule user.
amule  | /home/amule/.aMule/amule.conf file found. Using existing configuration.
amule  | /home/amule/.aMule/remote.conf file found. Using existing configuration.
amule  | [MOD_AUTO_RESTART] aMule will be restarted automatically (cron 0 6 * * *)... You can disable this mod with MOD_AUTO_RESTART_ENABLED=false
amule  | [MOD_FIX_KAD_GRAPH] Removing Kad stats graph to fix potential crash... You can disable this mod with MOD_FIX_KAD_GRAPH_ENABLED=false
amule  | [MOD_FIX_KAD_BOOTSTRAP] File nodes.dat already exist. You can disable this mod with MOD_FIX_KAD_BOOTSTRAP_ENABLED=false
amule  |  2023-11-18 20:55:37: Logging to stdout enabled
amule  |  2023-11-18 20:55:37: Initialising aMuleD 2.3.3 compiled with wxBase(GTK2) v3.2.2 and Boost 1.82
amule  |  2023-11-18 20:55:37: Checking if there is an instance already running...
amule  |  2023-11-18 20:55:37: No other instances are running.
amule  |  2023-11-18 20:55:37: Creditfile loaded, 0 clients are known
amule  |  2023-11-18 20:55:37: *** TCP socket (ECServer) listening on 0.0.0.0:4712
amule  |  2023-11-18 20:55:37: Created Server UDP-Socket at port 4665
amule  |  2023-11-18 20:55:37: ListenSocket: Ok.
amule  |  2023-11-18 20:55:37: Created Client UDP-Socket at port 4672
amule  |  2023-11-18 20:55:37: Loading server.met file: /home/amule/.aMule/server.met
amule  | !2023-11-18 20:55:37: 9 servers in server.met found
amule  |  2023-11-18 20:55:37: Loading temp files from /temp.
amule  |  2023-11-18 20:55:37: All PartFiles Loaded.
amule  |  2023-11-18 20:55:37: No part files found
amule  |  2023-11-18 20:55:37: No shareable files found in directory: /incoming
amule  |  2023-11-18 20:55:37: Found 0 known shared files
amule  | !2023-11-18 20:55:37: web server running on pid 43
amule  |  2023-11-18 20:55:37: amuled: OnInit - starting timer
amule  |  2023-11-18 20:55:37: Asio thread 1 started
amule  |  2023-11-18 20:55:37: Asio thread 2 started
amule  |  2023-11-18 20:55:37: Asio thread 3 started
amule  |  2023-11-18 20:55:37: Asio thread 4 started
amule  |  2023-11-18 20:55:37: Loading IP filters 'ipfilter.dat' and 'ipfilter_static.dat'.
amule  |  2023-11-18 20:55:37: New external connection accepted
amule  |  2023-11-18 20:55:37: Connecting client: aMuleweb 2.3.3
amule  |  2023-11-18 20:55:37: Access granted.
amule  |  2023-11-18 20:55:37: Loaded 226324 IP-ranges from '/home/amule/.aMule/ipfilter.dat'.
amule  |  2023-11-18 20:55:37: Loaded 0 IP-ranges from '/home/amule/.aMule/ipfilter_static.dat'.
amule  |  2023-11-18 20:55:37: IP filter is ready
amule  | !2023-11-18 20:55:37: Connecting
amule  |  2023-11-18 20:55:37: Connecting to eMule Security (5.45.85.226 - 5.45.85.226:6584) using protocol obfuscation.
amule  |  2023-11-18 20:55:37: Read 158 Kad contacts
amule  | !2023-11-18 20:55:37: Kad started.
amule  |  2023-11-18 20:55:37: Connected to eMule Security (5.45.85.226:6584)
amule  |  2023-11-18 20:55:37: 20:55:37: Error: Failed to unregister descriptor 22 from epoll descriptor 16 (error 2: No such file or directory)
amule  |  2023-11-18 20:55:37: 20:55:37: Error: Failed to unregister descriptor 22 from epoll descriptor 16 (error 2: No such file or directory)
amule  |  2023-11-18 20:55:37: Successfully updated ipfilter.dat
amule  |  2023-11-18 20:55:37: Loading IP filters 'ipfilter.dat' and 'ipfilter_static.dat'.
amule  |  2023-11-18 20:55:38: Loaded 226324 IP-ranges from '/home/amule/.aMule/ipfilter.dat'.
amule  |  2023-11-18 20:55:38: Loaded 0 IP-ranges from '/home/amule/.aMule/ipfilter_static.dat'.
amule  |  2023-11-18 20:55:38: IP filter is ready
amule  |  2023-11-18 20:55:38: Connecting to eMule Sunrise (176.123.5.89 - 176.123.5.89:4725) using protocol obfuscation.
amule  |  2023-11-18 20:55:38: Connected to eMule Sunrise (176.123.5.89:4725)
amule  | !2023-11-18 20:55:39: Kad stopped.
amule  | !2023-11-18 20:55:39: Connected to Kad (firewalled)
amule  |  2023-11-18 20:55:47: WARNING: eMule Security (5.45.85.226:6584) - NG : You have a lowid. Please review your network config and/or your settings.
amule  | !2023-11-18 20:55:47: Connection established on: eMule Security
amule  | !2023-11-18 20:55:47: Connected to eMule Security with LowID
amule  |  2023-11-18 20:55:47: New clientid is 384672
amule  | !2023-11-18 20:55:47: WARNING: You have received Low-ID!
amule  |  2023-11-18 20:55:47: 	Most likely this is because you're behind a firewall or router.
amule  |  2023-11-18 20:55:47: 	For more information, please refer to http://wiki.amule.org
amule  |  2023-11-18 20:55:47: ServerMessage: server version 17.15 (lugdunum)
amule  |  2023-11-18 20:55:47: ServerMessage: Welcome to eMule Security! <> www.emule-security.org
amule  |  2023-11-18 20:55:47: ServerMessage: Download Safe Serverlist > http://www.emule-security.org/serverlist/
amule  |  2023-11-18 20:55:47: ServerMessage: IP-filter > http://www.emule-security.org/e107_plugins/faq/faq.php?0.cat.2.1
amule  |  2023-11-18 20:55:47: ServerMessage: nodes.dat > http://www.emule-security.org/e107_plugins/faq/faq.php?0.cat.6.6
amule  |  2023-11-18 20:55:47: ServerMessage: Ip-To-Country database> http://www.emule-security.org/e107_plugins/faq/faq.php?0.cat.7.10
amule  |  2023-11-18 20:55:47: ServerMessage: eMule MODs > http://www.emule-security.org/modb/
amule  |  2023-11-18 20:55:47: ServerMessage: Disclaimer: This server is only indexing file-hashes, and no contains any files,
amule  |  2023-11-18 20:55:47: ServerMessage: not directly involved in the exchange of files between users of p2p-network.
amule  |  2023-11-18 20:55:47: ServerMessage: Administration of server is not responsible for the contents of files
```
Why is amule searching its config file in `/home/amule/.aMule/amule.conf`? There's only one user in my system and it's not "amule" so this folder does not exist nor the user amule. The lowID and the firewalled Kad is a consequence of this issue since amule is using its default config and not using the open ports in my router (59000 tcp and 59003 udp).

As you can already imagine by now, I'm not an experienced Docker user.
