### ISSUE TITLE
always Low ID

### ISSUE THREAD

**Issue by Destroyer061090** [ngosang/docker-amule#59]
I have used below setup and correctly open the router port, however I alwasys have LowID....

Making some tests, I recognized that if I set "network_mode: "host"" than i'm not able to enter on the UI interface but on docker log I can see the HighID... normally on my windows I use standard eMule and not eMule Adunanza... I don't know if something related... I really dont know what to do...

```
---
version: "2.1"
services:
  amule:
    image: ngosang/amule
    container_name: amule
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Italy
      - GUI_PWD=mypwd
      - WEBUI_PWD=mypwd
      - MOD_AUTO_RESTART_ENABLED=true
      - MOD_AUTO_RESTART_CRON=0 6 * * *
      - MOD_AUTO_SHARE_ENABLED=false
      - MOD_AUTO_SHARE_DIRECTORIES=/incoming;/my_movies
      - MOD_FIX_KAD_GRAPH_ENABLED=true
      - MOD_FIX_KAD_BOOTSTRAP_ENABLED=true
    ports:
      - "34711:4711" # web ui 
      - "34712:4712" # remote gui, webserver, cmd ...
      - "4662:4662" # ed2k tcp
      - "4665:4665/udp" # ed2k global search udp (tcp port +3)
      - "4672:4672/udp" # ed2k udp
    volumes:
      - /volume1/docker/aMule/conf:/home/amule/.aMule
      - /volume1/docker/aMule/Incoming:/incoming
      - /volume1/docker/aMule/Temp:/temp
    restart: unless-stopped
```
